name = "RandomWalkBVP"
uuid = "114ffcdd-22b5-45a4-9385-909661964ad8"
authors = ["Miguel Raz Guzm√°n Macedo <miguelraz@ciencias.unam.mx> and contributors"]
version = "0.1.0"

[deps]
Folds = "41a02a25-b8f0-4f67-bc48-60067656b558"
FunctionWrappers = "069b7b12-0de2-55c6-9aab-29f3d0a68a2e"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Tullio = "bc48ee85-29a4-5162-ae0b-a64e1601d4bc"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
